# ================================================================================ #
#                         Author: Abderrahmane Abdelouafi                          #
#                              File Name: dockerfile                               #
#                      Creation Date: April 12, 2026 01:07 PM                      #
#                      Last Updated: August 14, 2026 01:07 PM                      #
#                           Source Language: properties                            #
#                                                                                  # 
#                              --- Code Description ---                            #
#       Ensure that the Apache server is configured to use SSL/TLS for secure      #
#   communication. It sets up both HTTP and HTTPS virtual hosts, redirects HTTP    #
#  traffic to HTTPS, and includes security headers to enhance the security of the  #
#   web application. It also specifies error handling and logging for both HTTP &  #
#                                  HTTPS requests.                                 #
# ================================================================================ #

ServerName __APP_DOMAIN__

<VirtualHost *:80>

    ServerName __APP_DOMAIN__
    __APP_DOMAIN_ALIASES__

    DocumentRoot /var/www/html

    RewriteEngine On

    RewriteCond %{REQUEST_METHOD} ^CONNECT$ [NC]
    RewriteRule ^ - [F,L]

    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://__APP_DOMAIN__%{REQUEST_URI} [R=301,L,NE]

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride FileInfo Options
        Require all granted

        <LimitExcept GET POST HEAD OPTIONS>
            Require all denied
        </LimitExcept>
    </Directory>

    ErrorLog /var/www/logs/apache/http-error.log
    CustomLog /var/www/logs/apache/http-access.log ias42
</VirtualHost>

<VirtualHost *:443>

    ServerName __APP_DOMAIN__
    __APP_DOMAIN_ALIASES__

    DocumentRoot /var/www/html

    SSLEngine On
    SSLProtocol -all +TLSv1.2 +TLSv1.3
    SSLHonorCipherOrder On
    SSLCompression Off
    SSLSessionTickets Off

    SSLCertificateFile /etc/apache2/ssl/certs/fullchain.pem
    SSLCertificateKeyFile /etc/apache2/ssl/private/server.key

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride FileInfo Options
        Require all granted

        <LimitExcept GET POST HEAD OPTIONS>
            Require all denied
        </LimitExcept>
    </Directory>

    <IfModule mod_headers.c>
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set Referrer-Policy "strict-origin-when-cross-origin"
        Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"
        Header always set Content-Security-Policy "frame-ancestors 'self';"
        Header always set Strict-Transport-Security "max-age=31536000"
    </IfModule>

    ErrorDocument 400 /frontend/errors/handler.php
    ErrorDocument 401 /frontend/errors/handler.php
    ErrorDocument 403 /frontend/errors/handler.php
    ErrorDocument 404 /frontend/errors/handler.php
    ErrorDocument 408 /frontend/errors/handler.php
    ErrorDocument 413 /frontend/errors/handler.php
    ErrorDocument 500 /frontend/errors/handler.php
    ErrorDocument 503 /frontend/errors/handler.php

    ErrorLog /var/www/logs/apache/https-error.log
    CustomLog /var/www/logs/apache/https-access.log ias42
</VirtualHost>
